"""
monvisor/cli/nginx.py
Phase 4 — nginx reverse-proxy config generation.

Builds the conf that fronts Grafana (/) and the MonVisor UI (/monvisor/),
prints it, and offers to write it to the nginx conf.d directory (with confirm).
Falls back to writing into ~/.monvisor/ when /etc/nginx is not writable.
"""

from __future__ import annotations

from pathlib import Path

from rich.console import Console
from rich.prompt import Confirm
from rich.syntax import Syntax

from monvisor import config
from monvisor.db import queries

console = Console()

NGINX_TARGET = Path("/etc/nginx/conf.d/monvisor.conf")


def build_config(grafana_url: str, web_port: int) -> str:
    """Render the nginx server block as a string."""
    return f"""# MonVisor nginx configuration
# Generated by monvisor
# Place in {NGINX_TARGET}

server {{
    listen 443 ssl;
    server_name _;

    ssl_certificate     /etc/ssl/certs/monvisor.crt;
    ssl_certificate_key /etc/ssl/private/monvisor.key;

    # Grafana
    location / {{
        proxy_pass {grafana_url};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }}

    # MonVisor web UI
    location /monvisor/ {{
        proxy_pass http://127.0.0.1:{web_port}/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }}
}}

server {{
    listen 80;
    return 301 https://$host$request_uri;
}}
"""


def _resolve_grafana_url(environment: str | None) -> str:
    """Prefer the environment's grafana_url, then the global setting, then default."""
    if environment:
        env = queries.get_environment(environment)
        if env and env.get("grafana_url"):
            return env["grafana_url"].rstrip("/") + "/"
    setting = queries.get_setting("grafana-url")
    if setting:
        return setting.rstrip("/") + "/"
    return "http://127.0.0.1:3000/"


def emit_nginx_config(environment: str | None = None, offer_write: bool = True) -> str:
    """Print the nginx config and (optionally) offer to write it."""
    grafana_url = _resolve_grafana_url(environment)
    conf = build_config(grafana_url, config.WEB_PORT)

    console.print(Syntax(conf, "nginx", theme="ansi_dark", background_color="default"))

    if not offer_write:
        return conf

    if not Confirm.ask(f"\n  Write this to {NGINX_TARGET}?", default=False):
        console.print("  [dim]Not written. Copy the block above manually if you prefer.[/dim]")
        return conf

    try:
        NGINX_TARGET.parent.mkdir(parents=True, exist_ok=True)
        NGINX_TARGET.write_text(conf, encoding="utf-8")
        console.print(f"  [green]\u2713[/green] Wrote {NGINX_TARGET}")
        console.print("  [dim]Reload nginx:  sudo nginx -t && sudo systemctl reload nginx[/dim]")
    except PermissionError:
        fallback = config.MONVISOR_HOME / "monvisor.conf"
        fallback.write_text(conf, encoding="utf-8")
        console.print(f"  [yellow]\u26a0[/yellow]  No permission for {NGINX_TARGET}. Wrote to {fallback} instead.")
        console.print(f"  [dim]Install it with:  sudo mv {fallback} {NGINX_TARGET}[/dim]")
        console.print("  [dim]Then:  sudo nginx -t && sudo systemctl reload nginx[/dim]")

    return conf
